---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: docker.io/lorisrossi/vpa-recommender:0.4.0
        command:
        - /recommender
        args:
        - --v=-1
        - --stderrthreshold=info
        - --recommender-interval=30s
        - --control-core-max=5
        - --pod-recommendation-min-cpu-millicores=100
        - --control-replicas=3
        - --control_sla=0.6
        - --control-a=0.5
        - --control-memory=25000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080
